-- MySQL Script generated by MySQL Workbench
-- Mon May 20 17:04:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema confeitaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema confeitaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `confeitaria` DEFAULT CHARACTER SET utf8mb4 ;
USE `confeitaria` ;

-- -----------------------------------------------------
-- Table `confeitaria`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confeitaria`.`clientes` (
`id` INT(11) NOT NULL AUTO_INCREMENT,
`nome` VARCHAR(45) NOT NULL,
`numero` VARCHAR(45) NOT NULL,
PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `confeitaria`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confeitaria`.`pedidos` (
`id` INT(11) NOT NULL AUTO_INCREMENT,
`id_cliente` INT(11) NOT NULL,
`tamanho` VARCHAR(45) NOT NULL,
`data_para_entrega` DATE NOT NULL,
`observacoes` VARCHAR(100) NOT NULL,
PRIMARY KEY (`id`),
INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `confeitaria`.`clientes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
